### ISSUE TITLE
Modifications to the search demo

### ISSUE THREAD

**Issue by NeilWeingarten** [UCDavisLibrary/ucd-library-search#1]
On the "Library Catalogs" button please make the following changes:

- Add a checkbox for "Include Articles" that triggers a search on the "Everything" tab in Primo (will be renamed to "Catalog + Articles" soon).  http://search.library.ucdavis.edu/primo_library/libweb/action/search.do?mode=Basic&vid=01UCD_V1&tab=default_tab&
- Add links to Advanced Search and Browse Search.  These should link directly to the advanced search and browse search screens in Primo.  Browse search should link to http://search.library.ucdavis.edu/primo_library/libweb/action/search.do?fn=showBrowse&mode=BrowseSearch&vid=01UCD_V1 .  If the "Include Articles" checkbox is checked, then Advanced search should link to the "Everything" version (http://search.library.ucdavis.edu/primo_library/libweb/action/search.do?mode=Advanced&ct=AdvancedSearch&vid=01UCD_V1&tab=default_tab&dscnt=0&dstmp=1494354497993), otherwise to the "Library Catalog" version (http://search.library.ucdavis.edu/primo_library/libweb/action/search.do?mode=Advanced&ct=AdvancedSearch&vid=01UCD_V1&tab=catalog_tab&dscnt=0&dstmp=1494354680938)

Add a button for Course Reserves that allows people to search the course reserves tab in Primo: http://search.library.ucdavis.edu/primo_library/libweb/action/search.do?mode=Basic&vid=01UCD_V1&tab=ucd_course_reserves&

Under Course Reserves, add links to Primo Advanced Search (http://search.library.ucdavis.edu/primo_library/libweb/action/search.do?mode=Advanced&ct=AdvancedSearch&vid=01UCD_V1&tab=ucd_course_reserves&dscnt=0&dstmp=1494354727529) and Browse Search (http://search.library.ucdavis.edu/primo_library/libweb/action/search.do?fn=showBrowse&mode=BrowseSearch&vid=01UCD_V1)

**Comment by jrmerz** [comment]
Started here 9865263f282650a68b94e041d6efbf11d84565db

**Comment by NeilWeingarten** [comment]
Marking as resolved since the course reserves items have been moved and other items are done.
