### ISSUE TITLE
New primo Search

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ucd-library-search#10]
The Library search should be updated to the new primo search API.  These are documented for [dlSearch.do](https://knowledge.exlibrisgroup.com/Primo/Knowledge_Articles/Make_a_Search_Box_using_Primo_Deep_Links_(dlSearch.do))  and for [primo-explore/search](https://knowledge.exlibrisgroup.com/Primo/Product_Documentation/New_Primo_User_Interface/New_UI_Customization_-_Best_Practices#Creating_a_Search_Box_With_Deep_Links_to_the_New_UI).  Both of these applications make reference to a number of additional search tabs, etc.  This can be gleaned from the [new default page](https://search.library.ucdavis.edu/primo-explore/search?vid=01UCD_V1&lang=en_US&sortby=rank).  But you can also see these tabs on the Primo backend site as shown below.

![screenshot from 2017-08-08 15-51-46](https://user-images.githubusercontent.com/344953/29100394-23532512-7c60-11e7-8e3c-5a4947cd02d5.png)

![screenshot from 2017-08-08 15-51-27](https://user-images.githubusercontent.com/344953/29100405-2af0e14c-7c60-11e7-9750-3cdaf100cc69.png)

**Comment by jrmerz** [comment]
fixes pushed to lib-ucd dev
