### ISSUE TITLE
Add Search Tips for Primo Search Tab

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ucd-library-search#12]
The Primo Search tab should include a 'Search Tips` that points to /library-search-faq
rt #55432

**Comment by qjhart** [comment]
@wrenaria please add images

**Comment by wrenaria** [comment]
Here's images showing link placement and how it should break as the screen shrinks:

![searchtipsartboard 6](https://user-images.githubusercontent.com/17831969/32245523-3b449618-be39-11e7-860e-13694202788f.png)

**Comment by pbrantley** [comment]
that looks good
