### ISSUE TITLE
Suggested updates to the Search Language

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ucd-library-search#14]
We have the following suggestions about potential changes to search descriptions in the search bar.  [Source](https://drive.google.com/file/d/1Derbhk8vibQOwbhdxg7SOWt13UkiR1ga/view) Comments #1,#2.

![image](https://user-images.githubusercontent.com/344953/33634638-b766b496-d9c9-11e7-9166-b2f59a2fea9a.png)

**Comment by qjhart** [comment]
@wrenaria Kimmy, can you please review, and weigh in these revisions.  I know that we just updated one of the search descriptions.

**Comment by wrenaria** [comment]
I think nearly all of these revision suggestions are good ones. There's two alterations I would make to the descriptions and one suggestion I would not do. 

### Site Search
For the Site Search description - I agree it might be helpful to be clearer that it's the library web pages that are being searched, but I also think it's helpful to have that list of type of results they might expect to see when searching. Maybe change to something like...

**Search library web pages for resources such as research guides, manuscripts and archives, services, and people.**

### Course Reserves
For Course Reserves, perhaps we can make it a combo of what's there currently and the revision suggestion:

**Find required and/or recommended reading materials put on reserve by your instructor or TA via course number (e.g. ENL-003) or title.**

The suggestion we should NOT do is the one to add the link "Instructors: How To Place Materials On Reserve." I don't think the search box is the place to host that. Not only is it very wordy link text, it doesn't relate directly to using search.

**Comment by pbrantley** [comment]
agree with both
