### ISSUE TITLE
Add shortcuts to popular databases

### ISSUE THREAD

**Issue by wrenaria** [UCDavisLibrary/ucd-library-search#15]
Looking at Analytics has shown us that there are some Databases that are sought out much more frequently than others (PubMed, for example). In order to make finding these standouts a little quicker, I think we should include the top 4-5 popular databases as shortcut links in the search box.

## Option 1:
This is a simplest change. Add "Popular" database links underneath the existing browsable alphabet. 

### Desktop

![databasesearchalphabet-100](https://user-images.githubusercontent.com/17831969/33789116-554f07fe-dc2b-11e7-9cf5-06ee89e2274e.jpg)

### Mobile

![databasesearchalphabetmobile-100](https://user-images.githubusercontent.com/17831969/33789120-5c092a8e-dc2b-11e7-9357-39ac574866db.jpg)

## Option 2:
Reduce the browsable alphabet to a simple "Browse A-Z" shortcut to the alphabetically indexed pages, without actually showing all the alphabetical letters to reduce visual clutter. It's a little less overwhelming to look at for the user.

### Desktop

![databasesearchshortcuts-100](https://user-images.githubusercontent.com/17831969/33789122-60da7518-dc2b-11e7-913d-f0b914216a88.jpg)

### Mobile

![databasesearchshortcutsmobile-100](https://user-images.githubusercontent.com/17831969/33789126-657ad8b0-dc2b-11e7-9e6c-e82ffd1750ea.jpg)

I'm inclined to go with option 2 for a cleaner appearance, though option 1 may be less contentious for other library parties. Either solution is fine so whatever our OS group prefers is good with me.

**Comment by pbrantley** [comment]
I'm up for Option 2.

**Comment by wrenaria** [comment]
Err, I just realized that the Option 2 would require a change to how the [Alphabetical Database Browsing](https://www.library.ucdavis.edu/az-database/a/) looks, since it currently keeps the search box in place and uses the alphabetical indexing located within it. 

So if we go with Option 2, we would need to bring in alphabetical indexing another way, perhaps similar to how it is implemented on [Manuscripts](https://www.library.ucdavis.edu/special-collections/az-manuscripts/a/). Ideally, we'd hide the "Browse" button in when in browse mode too. 

@jrmerz can weigh in on how annoying that is or isn't to implement...

This might look like:

![datasearch-embed](https://user-images.githubusercontent.com/17831969/36234516-3e747ab4-11a0-11e8-8bcd-f15803266e84.png)

Or like:

![datasearch-float](https://user-images.githubusercontent.com/17831969/36234522-4260495a-11a0-11e8-8636-3eac1ea4450f.png)


In these solutions I've added and "All" button and a "#" button, two options currently lacking from our Browse capability.

**Comment by jrmerz** [comment]
@wrenaria So the final screenshot is what I should be building?

@qjhart @wrenaria we have a verdict on the **popular** list?

**Comment by wrenaria** [comment]
@jrmerz Yes, the final screenshot. 

Popular list should be whatever are top hits are according to analytics.

**Comment by jrmerz** [comment]
@wrenaria How is the database browse bar work on the home page?

**Comment by wrenaria** [comment]
Discussed on Slack, including here for documentation.

The alphabetical browse bar only exists on database pages. It is not included on the homepage or anywhere else the search bar exists outside of the database pages. The "A-Z Browse" link takes users to the base database page.

**Comment by jrmerz** [comment]
@wrenaria @qjhart so top 5 search for dbs are:

- pubmed (single)
- proquest (many)
- web of science (many)
- psycinfo (single)
- biosis (single)

but proquest and web of science are not single databases, so there is no single link I can provide. Sooo do you want those two links to perform a search?  Other option is to keep moving down the list until we hit single database result searches?

Next items:
 - biosis (single)
 - proquest historical news (many)
 - jstor (two)
 - worldcat (single)

thoughts?

**Comment by jrmerz** [comment]
FYI, I have pushed a demo to beta

**Comment by qjhart** [comment]
My inclination is to perform the search.  Then they see there are many, I don't know how to let them know ahead of time that the links behave differently however.  I think otherwise, they'd think proquest, for example has only one db.

**Comment by jrmerz** [comment]
@qjhart FYI, I used that strategy in the first demo pushed to beta

**Comment by wrenaria** [comment]
Performing the search seems like a good solution to me. 

For the numbers on the A-Z nav, can you group all numbers under a " # " symbol instead of by individual numbers like 1, 3 ?

Also if you could add more padding to the left and right side of "ALL", that'd be great (maybe like 5px to each side?). It feels a little squished.

**Comment by jrmerz** [comment]
The '#' sign might require rebuilding the database a-z index.  @qjhart ?

**Comment by jrmerz** [comment]
Ok made the ALL button bigger and rebuilt the a-z index for databases.  All numbers are now grouped to '#'.

@qjhart can you double check I did the upgrade correctly using the wordpress transient value. https://github.com/UCDavisLibrary/ucd-lib/blob/dev/wp-content/themes/ucd-lib/functions/letter-to-tax.php#L74 . That's how I found to do it in a blog post (apparently the same blog post the author of this file used :) )

**Comment by wrenaria** [comment]
@jrmerz Looks great except there is a 1 and 3 remaining in the alphabet list that shouldn't be there.

**Comment by jrmerz** [comment]
nice catch, fixed the indexing script.  They should be gone now
