### ISSUE TITLE
Make the buttons more buttony

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ucd-library-search#16]
@wrenaria has identified that some users don't recognize that the search bar buttons are actually buttons.  One quick idea was to replicate that highlight you get from that tabulation through those buttons.  @amyazzarito wondered if a more buttony look is appropriate

**Comment by jrmerz** [comment]
@wrenaria fyi, new button hover pushed to beta.  Let me know if there is any additional design modification you want.

**Comment by wrenaria** [comment]
@jrmerz The button hover is perfect. I don't desire/see the need to make any more button design changes unless further testing with users suggests we should.
