### ISSUE TITLE
Next updates to the search demo

### ISSUE THREAD

**Issue by NeilWeingarten** [UCDavisLibrary/ucd-library-search#2]
- Add a button for Course Reserves that allows people to search the course reserves tab in Primo: http://search.library.ucdavis.edu/primo_library/libweb/action/search.do?mode=Basic&vid=01UCD_V1&tab=ucd_course_reserves&  - This should be placed between "Library Catalogs" and "Databases"
- Under Course Reserves, add links to Primo Advanced Search (http://search.library.ucdavis.edu/primo_library/libweb/action/search.do?mode=Advanced&ct=AdvancedSearch&vid=01UCD_V1&tab=ucd_course_reserves&dscnt=0&dstmp=1494354727529) and Browse Search (http://search.library.ucdavis.edu/primo_library/libweb/action/search.do?fn=showBrowse&mode=BrowseSearch&vid=01UCD_V1)
- Under Databases, remove the "by category" option and replace with a free-text search bar.  Should result in a results page similar to https://www.library.ucdavis.edu/az-database/d/
- Remove the Calisphere search option
- Rename the "Melvyl" search option to "All UC Libraries (Melvyl)"
- Add a search option for "Subject and Course Guides" that functions the same as the "Site Search" option but limits results to pages with a content type of Guides.  This should be placed between "Melvyl" and "Site Search."
- Rename the "Library Catalogs" search option to "Library Catalog"
- On the "Library Catalogs" search option, make the checkbox more visible: maybe slightly larger and placed left aligned directly below the search box?  Should be an obvious option.

**Comment by jrmerz** [comment]
updates pushed to [demo](https://ucdavislibrary.github.io/ucd-library-search/demo.html)

**Comment by NeilWeingarten** [comment]
Looks good - closing.
