### ISSUE TITLE
Reverse search options on "Library Catalog"

### ISSUE THREAD

**Issue by NeilWeingarten** [UCDavisLibrary/ucd-library-search#3]
As suspected - need to switch the order of the way library catalog works.  To this extent:

- Change button name to "Library Catalog + Articles"
- Change hint text to "Search Library Catalog + Articles"
- Change checkbox text to "Library Catalog only"
- Reverse what searches what: default should search the everything (catalog + articles) tab of primo, checked box should search the catalog tab of primo.  Advance search links should also be changed to match.

**Comment by jrmerz** [comment]
updates pushed to [demo](https://ucdavislibrary.github.io/ucd-library-search/demo.html)

**Comment by NeilWeingarten** [comment]
Some changes still needed:
 - Change hint text to "Search Library Catalog + Articles"
 - Shift the "Library Catalog Only" Checkbox to a more prominent position, make slightly larger.

**Comment by jrmerz** [comment]
@NeilWeingarten updates pushed to demo

**Comment by NeilWeingarten** [comment]
Looks good - closing.
