### ISSUE TITLE
Final Set (should be) of issues to resolve before we start going live

### ISSUE THREAD

**Issue by NeilWeingarten** [UCDavisLibrary/ucd-library-search#4]
- When searching for a database, the results page has the search word listed in a separate box at the top - this shouldn't show up.
  - Also when searching for a database, the results have truncated descriptions and a "view database" button.  We should either remove the truncation, or keep the truncation and change the "view database" button to "Read More" which expands the description.
 - On the database search results page, the right column is the old search option box.  This is probably just due from resulting on the current site, but just calling it out.
 - Doing a search in the "Subjects and Course Guides" option results in a Primo search, rather than a website search limited to content with a "Guide' type.
 - Site Search needs to be improved: it should search all (published) content on the website.  For an example of it failing, compare a search of "ORCID" on the website against a google search of ORCID against our website: we only get 1 result when searching within our website.

**Comment by jrmerz** [comment]
@NeilWeingarten A lot of these sound like issues for the [library website repo](https://github.com/UCDavisLibrary/ucd-lib)?

As for 'Subjects and Course Guides' search.  I do not get the behavior described.  And you provide steps to reproduce as well as OS/browser.

**Comment by NeilWeingarten** [comment]
Sounds good - feel free to shift any you feel should be there to the Library Website Repo.

For "Subjects and Course Guides," I must have been in the wrong box - works now.  However, the results page brings up guides and keywords - should only bring up guides.  Also - do you know to what level it is searching?  Is it searching the content of each guide or just the titles / keywords associated?

**Comment by jrmerz** [comment]
Can you provide an example search where keywords show up?

Currently I am limiting the search to post_type=article (which is what system calls guides, not sure on the reason for that).  As for what content of the article type it's searching, I would have to defer to @qjhart for that.  My guess is this is just a standard wordpress search.

**Comment by NeilWeingarten** [comment]
Searching for "Biomedical" results in the following (Chrome):

![biomedical](https://cloud.githubusercontent.com/assets/17069741/26007328/e2825202-36f4-11e7-93c7-9cdc9eeab39f.png)

**Comment by jrmerz** [comment]
This looks like a bug for the website repo as well.
