### ISSUE TITLE
Arrow Keys do not work properly

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ucd-library-search#5]
I was typing in the search box and found that I couldn't move the cursor back using the left arrow key. It kept jumping back to the end of the typing string as soon as I released the key. Just thought I'd let someone know. 

Confirmed. Does the same thing for me but only in Chrome and Safari (win10 & macos) - left arrow is overridden. Firefox, MS Edge and IE all work normally for both OS.

**Comment by jrmerz** [comment]
Pushed to dev in website repo.  This change includes the merge of polymer-2.0 branch to master
