### ISSUE TITLE
Please point to https://search.library.ucdavis.edu/

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ucd-library-search#6]
The searches in the library currently point to http://search.library.ucdavis.edu.  They should instead be pointing to https://search.library.ucdavis.edu.  If any other redirects can be made to https:// that'd be good too.

**Comment by qjhart** [comment]
requested by @alexanderjslin

**Comment by jrmerz** [comment]
fixes pushed to lib-ucd dev
