### ISSUE TITLE
Milestone: Predefine Search Type on <ucd-library-search>

### ISSUE THREAD

**Issue by qjhart** [UCDavisLibrary/ucd-library-search#9]
[Milestone]: https://github.com/UCDavisLibrary/ucd-library-search/milestone/1
This [Milestone] extends the capabilties of the search component to all the default search selection to be  specified.  This would be both as a parameter or as a JavaScript call.

``` html
<ucd-library-search search_on="database">
```
An example application of this would be a modification to the library home page, so that we could have a url like `https://library.ucdavis.edu/?search_on=database`, and the `search_on` parameter would be updated on the ucd-library-search.

**Comment by qjhart** [comment]
@jrmerz let me know if this makes sense, and how long that would take.

**Comment by jrmerz** [comment]
Yup, makes sense.  Probably a little under a day to implement.

**Comment by qjhart** [comment]
@NeilWeingarten , I've added this to the [Library Project] planning document.  It's about a day to complete. Note, that you need to let us know if you want that capability on the index page alone, or on all pages.

[Library Project]: https://github.com/orgs/UCDavisLibrary/projects/5

**Comment by NeilWeingarten** [comment]
@qjhart To start, the homepage should be fine.  Once the initial change is made, how quickly can it be applied to other pages?
